version: "3.8"

services:
    # Serviço para o backend Laravel (com Vue.js)
    backend:
        build:
            context: .
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root

    # Serviço MySQL
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            # Não definir MYSQL_USER e MYSQL_PASSWORD para o root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
